### ISSUE TITLE
User info entry view

### ISSUE THREAD

**Issue by da-hye0** [imdangg/Imdangg-iOS#5]
### **Common**
**View**
- [x] CommonView
<img width="300" alt="스크린샷 2024-11-11 오후 11 03 53" src="https://github.com/user-attachments/assets/9b17bded-59d6-4c53-afee-e64a089d5c4d">

크기가 없는 공통 버튼.
CommonButtonState (type: enable, disable, unselectedBorderStyle, selectedBorderStyle)

---

### **UserInfoEntryView**

- [x] header
- [x] commonTextfield
- [x] 성별 버튼
- [x] 인풋 체크로직 추가(임시 로직만 추가됨)

---

### **Other**
- [x] #1  - Color + 추가 
- [x] keyboard extension(view 클릭시 키보드 내려감)

--- 
### **etc**
- [x] textfield focus 문제 해결중

**Comment by da-hye0** [comment]
**TODO**
HeaderView 아이콘 Y축 title과 맞추기
Common Textfiel의 clear button trailing 마진을 위해 right view 추가
